name: build

on:
  push:
    branches:
      - '*'
      - '!release-*'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  # zizmor: ignore[cache-poisoning, artipacked]
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      # zizmor: ignore[artipacked]
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        # zizmor: ignore[cache-poisoning]
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: prebuild
        run: scripts/prebuild.sh
      - run: npm install
      - name: npm install (button-angular)
        run: |
          cd src/button-angular
          npm install
      - run: npm run build:all
      - run: npm test
